### ISSUE TITLE
Could a LinkedIn share button be added?

### ISSUE THREAD

**Issue by kirsty-gasston** [rapidwebltd/direct-share-buttons#4]

**Comment by ojdon** [comment]
I've added LinkedIn share buttons in [this commit](https://github.com/rapidwebltd/intent-social-buttons/commit/b1b5a879e9152a5b7e29b4c61d9fdf891d2bee9b). I've also updated the [demo page](https://htmlpreview.github.io/?https://raw.githubusercontent.com/rapidwebltd/Intent-Social-Buttons/master/demo.html).

Closing.
